name: "Rust Code Coverage"
description: "A GitHub Action that does single-action code coverage generation."
author: "Arpad Borsos <arpad.borsos@googlemail.com>"
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  icon: "align-left"
  color: "green"

inputs:
  args:
    description: Arguments for the `cargo test` command. Defaults to `--workspace --all-features`.
    required: false
  toolchain:
    description: The rust toolchain to use. Defaults to current active toolchain.
    required: false
  output-format:
    description: The desired output format. One of `lcov`, `json`, `html` or `profdata`. Defaults to `lcov`.
    required: false
  output-filename:
    description: The desired output filename. Defaults to `coverage/coverage.$ext`, depending on the chosen `output-format`.
    required: false
